name: Repoclosure

on:
  workflow_dispatch:
  schedule:
    - cron: '25 9 * * *'

jobs:
  repoclosure:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - rawhide
          - 45
          - 44
    container:
      image: registry.fedoraproject.org/fedora:${{ matrix.version }}
    steps:
      - name: Prepare
        run: |
          dnf -y install --nodocs 'dnf5-command(repoclosure)'

          cat << 'EOF' >> /etc/yum.repos.d/coprs.repo
          [copr:copr.fedorainfracloud.org:solopasha:kde6-beta]
          name=Copr repo for kde6-beta owned by solopasha
          baseurl=https://download.copr.fedorainfracloud.org/results/solopasha/kde6-beta/fedora-${{ matrix.version }}-$basearch/
          type=rpm-md
          skip_if_unavailable=False
          gpgcheck=1
          gpgkey=https://download.copr.fedorainfracloud.org/results/solopasha/kde6-beta/pubkey.gpg
          repo_gpgcheck=0
          enabled=1
          enabled_metadata=1
          EOF

      - name: Repoclosure kde6-beta
        run: |
          dnf repoclosure \
            --check copr:copr.fedorainfracloud.org:solopasha:kde6-beta \
            --newest

      - name: Repoclosure kde6-beta (with --best)
        run: |
          dnf repoclosure \
            --check copr:copr.fedorainfracloud.org:solopasha:kde6-beta \
            --newest --best
